name: Build Markdown

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run build script
        run: python build.py

      - name: Upload output
        uses: actions/upload-artefact@v3
        with:
          name: markdown-output
          path: outputs
        
        
